### ISSUE TITLE
[1.7.10] Crash when creating a new world

### ISSUE THREAD

**Issue by HowardZHY** [pixfumy/Legacy-Elytras#5]
[crash-2022-10-14_13.55.35-client.txt](https://github.com/pixfumy/Legacy-Elytras/files/9782905/crash-2022-10-14_13.55.35-client.txt)

**Comment by pixfumy** [comment]
Which version of the mod are you using? What other mods?

**Comment by HowardZHY** [comment]
the latest one. see the report. I think LF API 1.8.0 breaks it. LF API 1.7.1 works fine for me.

**Comment by HowardZHY** [comment]
I don't think it crashes with LF API 1.9.0 anymore.
